### ISSUE TITLE
Touch outside to dismiss

### ISSUE THREAD

**Issue by tuanth89** [TakeoffAndroid/MaterialDialogSearchView#1]
Firstly, thank for your project.
How to dismiss when i touch outside dialog ???
I try toolbarSearchDialog.setCanceledOnTouchOutside(true) but not working.
Thanks.

**Comment by ckdevrel** [comment]
If you want to do it so simply give click event for view.

view.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        toolbarSearchDialog.dismiss();
    }
});

But for that purpose i have given back arrow option to close the dialog. Anyways use above snippet to close dialog while you touch outside.

**Comment by tuanth89** [comment]
Oh, really nice!!! I tried and it works like a charm.
I just like search Google Play :D.
Thanks.
